version: '3.8'

services:
  nodejs:
    build:
      context: ./aruba-connection
      dockerfile: Dockerfile.nodejs
    ports:
      - "3001:3001"

  # python:
  #   build:
  #     context: ./aruba-connection
  #     dockerfile: Dockerfile.python

  react:
    build:
      context: ./front-end
      dockerfile: Dockerfile.react
    ports:
      - "5173:5173"
