version: '3.8'

services:
  nodejs:
    build:
      context: ./nodejs
    ports:
      - "3001:3001"

  python:
    build:
      context: ./python

  react:
    build:
      context: ./react
    ports:
      - "5173:5173"
